### ISSUE TITLE
[Critical] Retency removes other files from s3 bucket

### ISSUE THREAD

**Issue by Glorf** [fdoxyz/martilla#18] opened 2019-11-16 19:20 UTC
Hi martilla, this last one is important, maybe even critical

I've been using one bucket, holding different backups of my services split into separate folders. When I put the backup into the bucket **martilla just counted the objects in the bucket and removed the oldest one** This is totally not acceptable and I was lucky that the file removed by the service was not important. Please, either fix the issue or **put this in bold in your documentation that you need separate s3 bucket for every service that is being backed up by martilla**

**Comment by fdocr** [comment] 2019-11-17 23:02
Indeed a big issue, I'll take a look into it. Thanks a lot for the report!

**Comment by fdocr** [comment] 2019-11-18 23:39
Hey @Glorf! Just in case you're interested in taking another look I just made available a release candidate with a fix for this problem (trying to avoid releasing more versions unless I'm confident the issue is properly fixed).

If you have some spare time I would inmensely appreciate if you can take a quick look at it, to make sure if you can't still reproduce the issue. The version to install is `0.4.0.rc`

**Closed as completed** 2019-11-27 15:57 UTC
Labels: bug

**Comment by Glorf** [comment] 2019-11-27 16:00
Thanks @fdoxyz, I'll update soon

**Comment by fdocr** [comment] 2019-11-27 16:19
Hi @Glorf, I actually just released `v0.4.0` after adding more tests. I believe it should be working as expected, but of course let me know if you find any other problems :)
